### ISSUE TITLE
Add feature to be able to retain the window size and specify coordinates when making borderless

### ISSUE THREAD

**Issue by yyIntsuki** [invcble/NoMoreBorder#1]
For instance, the window I'm running is 1920x810 (21:9). I would like to make the window borderless in 1920x810, as well as being able to specify them to align to a specific coordinate on my screen, for instance x=0, y=0.

This was a feature from Borderless Gaming that I really liked having and is essential when I use it.

Perhaps when unspecified, the default behavior should be either just specify to x=0, y=0 or place on center of screen?

**Comment by invcble** [comment]
All-right! I will work on this feature as soon as possible.

**Comment by invcble** [comment]
Feature added.
