### ISSUE TITLE
After a while NoMoreBorder no longer refreshes

### ISSUE THREAD

**Issue by TheRedfoox** [invcble/NoMoreBorder#11]
Opening the window drop-down menu leaves a list of items that are no longer up to date, whereas they should refresh every 2 seconds if I've understood correctly.

**Comment by invcble** [comment]
It's working perfectly fine in my testing, did you run it as admin?

**Comment by TheRedfoox** [comment]
At first no but for a few days I checked the box in the compatibility settings so I imagine it should be the same thing. Because otherwise the application reacts well to actions.

**Comment by TheRedfoox** [comment]
I have the impression that it's linked to an exit from standby or extended standby.
I've just got through the evening without any problems and I had turned my computer off completely last night.

**Comment by TheRedfoox** [comment]
I'm back to confirm that the problem is still with us in the long term. I'd say it happens fairly systematically after using a game that pushes the GPU load quite high.

**Comment by invcble** [comment]
In the underlying code, its just an for loop looking for new applications in a separate thread. My honest guess would be somehow in those scenarios, the loop goes out of execution and can't restate.

I will try to come up with a solution for this. Thanks for the bug report,.
