### ISSUE TITLE
being flagged as a trojan

### ISSUE THREAD

**Issue by yonatanku6** [invcble/NoMoreBorder#13]
Im sure it is safe as i see you actually work on updates and care about this just wanted to let you know it is flagged by smart screen and by virus total
![image_2024-10-13_104019725](https://github.com/user-attachments/assets/999170dc-21a6-4b22-876a-fd48101cb31a)
![image_2024-10-13_104050847](https://github.com/user-attachments/assets/a916ea22-4b86-48cb-80c2-ad24c4ce4cef)

**Comment by invcble** [comment]
I am aware of this, as someone else on reddit reported as well. My honest guess would be its just a false positive from the library codes used to compile the binary file.

Let me try to compile one using virtual environment and minimal packages and see if that helps.

**Comment by invcble** [comment]
![image](https://github.com/user-attachments/assets/46be59d1-a350-4b12-9c10-84c1e23d805c)

Nah it still get's flagged. Fresh venv did help in reducing the size to 18 mb though.

**Comment by invcble** [comment]
For future reference I will suggest anyone to have their own peace of mind, please compile your own exe from the main.py if possible. It's not much difficult, just install a python version and follow the steps in main page.

**Comment by SkyNinja** [comment]
@invcble 
It might be a good idea to pin this in case anyone else comes looking. I skimmed the code and didn't find anything malicious, so I assume it's the registry and documents access that is making that one vendor think it's a password stealer.
