### ISSUE TITLE
Multiple Monitor Support

### ISSUE THREAD

**Issue by Diviance** [invcble/NoMoreBorder#2]
Not everything I might want to use this on is something I want running on my primary monitor.  So it would be nice if I could choose which monitor to put it on if I have multiple monitors.

**Comment by invcble** [comment]
Since everyone has their monitors arranged differently, I have no idea how to actually pull that off. Did you try Win + Shift + Left/Right arrow keys to switch the application between monitors?

**Comment by Diviance** [comment]
Yes.  Your app just snaps it back to the main monitor (whichever one is set to the main monitor in Windows settings) immediately.

**Comment by invcble** [comment]
Can you try closing NoMoreBorder after you have set up the borderless window and then try switching to different screen?

**Comment by invcble** [comment]
Same here haha.
Did you ever try DisplayFusion? It's an popular paid app designed for that purpose. If you don't mind buying it, it could be your solution to all of that.

**Comment by Diviance** [comment]
I have DisplayFusion, I don't understand what it can do to fix the issue?  I mainly use it for the multi-monitor taskbar stuff so I don't know every little thing it can do.

**Comment by invcble** [comment]
This feature request has been addressed, thanks to [Code Witch](https://github.com/Aryuko). Will being closing it now.
