### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by andrewmd5** [invcble/NoMoreBorder#6]
Hi there,

Thank you for your work on this project. It's always exciting to see others tackle this problem and contribute to the community.

I noticed that you mentioned on [Reddit](https://www.reddit.com/r/pcmasterrace/comments/1bsukqy/i_made_a_free_alternative_for_borderless_gaming/) that this application was inspired by [Borderless Gaming](https://github.com/Codeusa/Borderless-Gaming). Given that you likely inspected the source code of Borderless Gaming for inspiration, this project would be considered a derivative work under the terms of the GPLv2 license.

As the creator and maintainer of Borderless Gaming, I kindly request that you:

1. Change your project's LICENSE to GPLv2
2. Provide proper attribution to the original Borderless Gaming project in accordance with the GPL

These steps will ensure that your project complies with the licensing terms of the original work it's derived from. This not only respects the open-source nature of Borderless Gaming but also helps maintain transparency in the development community.

If you have any questions about this or need assistance with implementing these changes, please don't hesitate to ask.

Thank you for your understanding and cooperation.

**Comment by invcble** [comment]
Thank you for reaching out and for your work on Borderless Gaming, which has indeed been an inspiration for my project, NoMoreBorder.

I would like to clarify that while my project was inspired by the functionality and concept of Borderless Gaming from an user's perspective, all of the code for NoMoreBorder was written independently and from scratch. I did not inspect or use any source code from Borderless Gaming in my project.

Given this, I believe NoMoreBorder is not a derivative work under the GPLv2, and I have therefore licensed it under the MIT license. I respect the open-source nature of Borderless Gaming and appreciate the inspiration it provided. If there are specific concerns or if there is something I might have overlooked, I am open to further discussion.
