### ISSUE TITLE
[Feature Request] Above Taskbar

### ISSUE THREAD

**Issue by yapthatsme** [invcble/NoMoreBorder#8]
Could you add a function to have the window above the taskbar? I have a monitor with a resolution of 2560x1080 and would like to play my games in 1920x1080 because I record Full HD gameplay. It would be fantastic if you could somehow get the scaled windows above the taskbar with your tool.

Otherwise everything works amazingly well! Thanks for your effort and the dark mode. :)

**Comment by invcble** [comment]
Did you try playing around with and X and Y offset?

**Comment by yapthatsme** [comment]
Yes, the two values are set to 321 and 0. Everything fits so far, only the taskbar is in front of the window and the only solution I currently have with your tool is to hide the taskbar, but that is rather suboptimal.
